main/urls.py
from django.urls import path, include
from django.conf.urls import url

from . import views
from .views import SearchResultsView
app_name = 'main'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path("register/", views.register, name="register"),
    path('<int:article_id>/vote/', views.vote, name='vote'),
    path('write/', views.write, name='write'),
    path('tinymce/', include('tinymce.urls')),
    path('search/', SearchResultsView.as_view(), name='search_results'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,32})/$',
        views.activate, name='activate'),
]

mywrite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User, AbstractBaseUser, BaseUserManager
from tinymce.models import HTMLField
from django.utils import timezone
import datetime
class Article(models.Model):
    title = models.CharField('כותרת',max_length=100)
    author = models.CharField('יוצר',max_length=50, default="first name")
    pub_date = models.DateTimeField('תאריך פרסום', auto_now_add=True)
    text = HTMLField('גוף',max_length=4000)
    votes = models.IntegerField('הצבעות' ,default=0)
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    def get_queryset(self):
        """Return the last five published questions."""
        return Article.objects.order_by('-pub_date')[:5]

# class Vote(models.Model):
#     user = models.ForeignKey(User)
#     article = models.ForeignKey(Article)

class MyAccountManager(BaseUserManager):
    def create_user(self, email, first_name, last_name, password=None):
        if not email:
            raise ValueError("למשתמש חייב להיות דואר אלקטרוני")
        if not first_name or not last_name :
            raise ValueError("למשתמש חייב להיות שם פרטי ושם משפחה ")

        user = self.model(
            email=self.normalize_email(email),
            first_name = first_name,
            last_name = last_name
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, first_name, last_name, password):
        user = self.create_user(
            email=self.normalize_email(email),
            first_name=first_name,
            last_name=last_name,
            password=password,
        )
        user.is_admin = True
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)

class Account(AbstractBaseUser):
    email = models.EmailField(verbose_name="דואר אלקטרוני", max_length=60, unique=True)
    first_name = models.CharField(verbose_name="שם פרטי" ,max_length=30)
    last_name = models.CharField(verbose_name="שם משפחה" ,max_length=30)
    date_joined = models.DateTimeField(verbose_name="תאריך הצטרפות" ,auto_now_add=True)
    last_login = models.DateTimeField(verbose_name="כניסה אחרונה למערכת", auto_now=True)
    is_admin = models.BooleanField(verbose_name="מנהל" ,default=False)
    is_active = models.BooleanField(verbose_name="פעיל" ,default=False)
    is_staff = models.BooleanField(verbose_name="עובד", default=False)
    is_superuser = models.BooleanField(verbose_name="משתמש עליון" ,default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name']

    objects = MyAccountManager()

    def __str__(self):
        return self.first_name + " " + self.last_name + ", " + self.email

    def has_perm(self, perm, obj=None):
        return self.is_admin

    def has_module_perms(self, app_label):
        return True

main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import Account, Article
from django.contrib.auth.models import User
from tinymce.widgets import TinyMCE
import datetime
class AccountCreationForm(UserCreationForm):
    class Meta:
        model = Account
        fields = ('first_name','last_name', 'email')

class ArticleCreationForm(forms.ModelForm): 
    # specify the name of model to use 
    # text = forms.Textarea(widget=TinyMCE(attrs={'cols': 80, 'rows': 30}))
    content = forms.CharField(widget=TinyMCE(attrs={'cols': 80, 'rows': 30}))
    class Meta: 
        model = Article 
        fields = '__all__'
        # widgets = {
        #     'text': forms.Textarea(attrs={'rows':18, 'cols':130}),
        # }
        exclude = ['votes', 'author']

main/views.py
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse, reverse_lazy
from django.views import generic
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.contrib.auth import logout, authenticate, login
from django.views.generic.edit import CreateView
from django.core.mail import EmailMessage
from django.contrib import messages
from django.views.generic import TemplateView, ListView
from django.contrib.auth.models import User
from django.core.mail import EmailMessage
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.db.models import Q
import datetime

from .forms import AccountCreationForm, ArticleCreationForm
from .models import Article, Account
from .token import account_activation_token

def index(request):
    latest_article_list = Article.objects.order_by('-votes')[:5]
    context = {'latest_article_list': latest_article_list}
    return render(request, 'main/index.html', context)


class DetailView(generic.DetailView):
    model = Article
    template_name = 'main/article.html'

# @login_required
def vote(request, article_id):
    article = get_object_or_404(Article, pk=article_id)
    article.votes += 1
    article.save()
    return JsonResponse(data = {"vote": "Voted! Thank you for the vote."})

def write(request):
    if request.user.is_authenticated:
        context = {} 
        # create object of form 
        form = ArticleCreationForm(request.POST) 
        # check if form data is valid 
        if request.method == "POST":
            if form.is_valid(): 
                article = form.save(commit=False) 
                article.author = request.user.first_name+' '+request.user.last_name # the user must be logged in for this.
                article.save()
            # save the form data to model 
    
        context['form']= form 
        return render(request, "main/article_creation_form.html", context) 
    else:
        return HttpResponse("calitol")

def register(request):
    if request.method == "POST":
        form = AccountCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.save()
            print(get_current_site(request))
            current_site = get_current_site(request)
            mail_subject = 'Activate your blog account.'
            message = render_to_string('main/acc_active_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid':urlsafe_base64_encode(force_bytes(user.pk)),
                'token':account_activation_token.make_token(user),
            })
            email = form.cleaned_data.get('email')
            email_message = EmailMessage(
                        mail_subject, message, to=[email]
            )
            email_message.send()
            messages.add_message(request, messages.INFO, 'שלחנו הודעה לדואר האלקטרוני שלך בה נמצא קישור להפעלת החשבון.')
            login(request, user)
            return HttpResponse("Please confirm your email address")
        else:
            for msg in form.error_messages:
                messages.error(request, f"{msg}: {form.error_messages[msg]}")

            return render(request = request,
                          template_name = "main/register.html",
                          context={"form":form})

    form = AccountCreationForm
    return render(request = request,
                  template_name = "main/register.html",
                  context={"form":form})

def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = Account.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, Account.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)
        # return redirect('home')
        return HttpResponse('Thank you for your email confirmation. Now you can login your account.')
    else:
        return HttpResponse('Activation link is invalid!')

class SearchResultsView(ListView):
    model = Article
    template_name = 'main/search_results.html'

    def get_queryset(self): # new
        query = self.request.GET.get('q')
        return Article.objects.filter(
            Q(title__icontains=query) | Q(author__icontains=query)
        )

main/templates/main/acc_active_email.html
{% autoescape off %}
Hi {{ user.first_name }},
Please click on the link to confirm your registration,
http://{{ domain }}{% url 'main:activate' uidb64=uid token=token %}
{% endautoescape %}

main/templates/main/article.html
{% extends 'base.html' %}

{% block content %}
<title>{{ article.title }}</title>
    <h1>{{ article.title }}</h1>
    <h3>{{ article.author }} - {{ article.pub_date | date:"d בF Y" }}</h3>
    <h4>{{ article.text | safe }}</h4>
<div>
<p>יש למאמר זה <strong><span id="total_votes">{{article.votes}}</span></strong> הצבעות</p>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    <button id="vote" class="button">הצבע</button>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script>
        $("#vote").click(function (e) {
          e.preventDefault()
          var upvotes = $("#total_votes").html()
          var updatedUpVotes = parseInt(upvotes) + 1
          $("#total_votes").html(updatedUpVotes)
          $.ajax({
            url: 'vote/',
            method: "GET",
            data: {},
            success: function (data) {
              console.log(data)
            },
            error: function (error) {
              console.log(error)
            }
          })
        })
      </script>
</div>
{% endblock content %}

main/templates/main/article_creation_form.html
{% extends 'base.html'%}
{% block content %}
{% load crispy_forms_tags %}
<h1>כתוב מאמר</h1>
<br>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
  <button type="submit" class="button">Save changes</button>
</form>
<!-- אם יש לך חשבון <a href="/login" target="blank"><strong>היכנס</strong></a> במקום. -->
{% endblock %}

main/templates/main/index.html
{% include 'base.html'%}
{% block head %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/index.css' %}">
{% endblock head %}
{% block header %}
<header>
</header>
{% endblock header %}
    {% block content %}
    <body>
    <title>זאת זכותך לכתוב</title>
    {% if latest_article_list %}
    {% for article in latest_article_list %}
    <div id="article-box" class="callout-primary"> 
        <a id="box-link" href="/{{ article.id }}/">
                <h1>{{article.title}}</h1>
                <div>
                    <h2>{{article.author}} - {{ article.pub_date | date:"d בF Y" }}</h3>
                </div>
                <div id="desription" class="callout primary">
                    <p>{{article.text}}</p>
                </div>
    </a>
    </div>
    {% endfor %} 
{% else %}
    <p>אין מאמרים זמינים כרגע...</p>
{% endif %}
</body>
{% endblock content %}

main/templates/main/login.html
{% extends 'base.html' %}

{% block title %}היכנס{% endblock %}

{% block content %}
<h2>היכנס</h2>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Login</button>
</form>
{% endblock %}

main/templates/main/register.html
{% extends 'base.html'%}
{% block content %}
{% load crispy_forms_tags %}
<h2>הירשם</h2>
<br>
<form method="post"> {% csrf_token %}
  {{ form|crispy }}
  {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
  <label for="remember">Remember me</label>
              <button type="submit">הירשם</button>
</form>
אם יש לך חשבון <a href="/login" target="blank"><strong>היכנס</strong></a> במקום.
{% endblock %}

main/templates/main/search_results.html
{% include 'base.html'%}
    {% block content %}
    {% if article_list %}
        {% for article in article_list %}
        <div id="article-box" class="callout"> 
            <a id="box-link" href="/{{ article.id }}/">
                    <h1>{{article.title}}</h1>
                    <div>
                        <h2>{{article.author}} - {{ article.pub_date | date:"d בF Y" }}</h3>
                    </div>
                    <div id="desription" class="callout primary">
                        <p>{{article.text | safe}}</p>
                    </div>
        </a>
        </div>
        {% endfor %}
    {% else %}
        <p>אין מאמרים שתואמים לחיפוש שלך</p>
    {% endif %}
        {% endblock %}
  